-- YASHIKA COMPUTERS V6 - SUPABASE DATABASE FOUNDATION
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- IMPORTANT:
-- 1) Never put service_role key in the browser.
-- 2) Frontend uses only the public anon key.
-- 3) RLS protects admin-only write/read operations.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'customer'
    check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text not null default '',
  category text not null,
  brand text not null default 'Custom',
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) not null default 0 check (old_price >= 0),
  badge text not null default 'Deal',
  stock text not null default 'In Stock'
    check (stock in ('In Stock', 'Low Stock', 'Out of Stock', 'Build to Order')),
  condition text not null default 'Refurbished',
  warranty text not null default 'Ask store*',
  rating numeric(2,1) not null default 4.5
    check (rating >= 0 and rating <= 5),
  image text not null default '',
  specs jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  display_id text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  customer jsonb,
  pincode text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  coupon text,
  status text not null default 'New'
    check (status in ('New', 'Contacted', 'Confirmed', 'Completed', 'Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- Create a profile automatically whenever a new Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, email, role)
  values (new.id, new.email, 'customer')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- SECURITY DEFINER helper used by RLS policies.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = (select auth.uid())
      and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;

-- Profiles: users can read their own profile. Admins can read all.
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.is_admin())
);

-- Products: storefront is public read.
drop policy if exists "products_public_read" on public.products;
create policy "products_public_read"
on public.products
for select
to anon, authenticated
using (is_active = true or (select public.is_admin()));

-- Products: only admin may insert/update/delete.
drop policy if exists "products_admin_insert" on public.products;
create policy "products_admin_insert"
on public.products
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "products_admin_update" on public.products;
create policy "products_admin_update"
on public.products
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "products_admin_delete" on public.products;
create policy "products_admin_delete"
on public.products
for delete
to authenticated
using ((select public.is_admin()));

-- Orders: storefront can create an enquiry order.
-- Admin is the only role that can list/update/delete orders.
drop policy if exists "orders_storefront_insert" on public.orders;
create policy "orders_storefront_insert"
on public.orders
for insert
to anon, authenticated
with check (
  jsonb_typeof(items) = 'array'
  and jsonb_array_length(items) between 1 and 50
  and total >= 0
);

drop policy if exists "orders_admin_select" on public.orders;
create policy "orders_admin_select"
on public.orders
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update"
on public.orders
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "orders_admin_delete" on public.orders;
create policy "orders_admin_delete"
on public.orders
for delete
to authenticated
using ((select public.is_admin()));

-- Seed products only if the products table is currently empty.
insert into public.products
(name, subtitle, category, brand, price, old_price, badge, stock, condition, warranty, rating, image, specs, sort_order)
select *
from (
  values
  (
    'Dell Latitude 7410',
    'Core i7 10th Gen · 32GB · 512GB NVMe',
    'Refurbished Laptop',
    'Dell',
    37000::numeric,
    140000::numeric,
    'Best Value',
    'In Stock',
    'Refurbished',
    'Up to 6 months*',
    4.8::numeric,
    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=85',
    '{"Processor":"Intel Core i7 10th Gen","Memory":"32GB DDR4","Storage":"512GB NVMe SSD","Display":"14-inch Full HD","OS":"Windows 11 Pro","Use":"Business / Coding / Office"}'::jsonb,
    10
  ),
  (
    'HP ProBook 440 G8',
    'Core i5 11th Gen · Windows 11 Pro',
    'Refurbished Laptop',
    'HP',
    26000::numeric,
    98000::numeric,
    'Hot Deal',
    'Low Stock',
    'Refurbished',
    'Up to 6 months*',
    4.7::numeric,
    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=85',
    '{"Processor":"Intel Core i5 11th Gen","Memory":"16GB DDR4","Storage":"512GB SSD","Display":"14-inch Full HD","OS":"Windows 11 Pro","Use":"Study / Office / Business"}'::jsonb,
    20
  ),
  (
    'MacBook Pro M1 Pro',
    '14-inch · 16GB · 512GB SSD',
    'MacBook',
    'Apple',
    70000::numeric,
    145000::numeric,
    'Premium',
    'In Stock',
    'Pre-owned',
    'Store warranty*',
    4.9::numeric,
    'https://images.unsplash.com/photo-1511385348-a52b4a160dc2?auto=format&fit=crop&w=1200&q=85',
    '{"Processor":"Apple M1 Pro","Memory":"16GB Unified","Storage":"512GB SSD","Display":"14-inch Liquid Retina XDR","OS":"macOS","Use":"Editing / Development / Creative"}'::jsonb,
    30
  ),
  (
    'Custom i5 Desktop',
    '8th Gen · 8GB DDR4 · 256GB SSD',
    'Desktop',
    'Custom',
    20900::numeric,
    29900::numeric,
    '3Y Warranty*',
    'Build to Order',
    'Custom Build',
    'Up to 3 years on selected parts*',
    4.8::numeric,
    'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=1200&q=85',
    '{"Processor":"Intel Core i5 8th Gen","Memory":"8GB DDR4","Storage":"256GB SSD","Graphics":"Integrated / Upgradeable","Cabinet":"Custom","Use":"Office / Billing / Study"}'::jsonb,
    40
  )
) as seed
(
  name, subtitle, category, brand, price, old_price, badge, stock,
  condition, warranty, rating, image, specs, sort_order
)
where not exists (select 1 from public.products);

-- ============================================================
-- AFTER YOU CREATE YOUR ADMIN USER IN:
-- Supabase Dashboard -> Authentication -> Users
--
-- Run this once, replacing the email:
--
-- update public.profiles
-- set role = 'admin'
-- where email = 'YOUR_ADMIN_EMAIL@gmail.com';
-- ============================================================
