export const categories = [
  "All",
  "Refurbished Laptop",
  "MacBook",
  "Desktop",
  "Gaming",
  "Components",
];

export const products = [
  {
    id: 1,
    name: "Dell Latitude 7410",
    subtitle: "Core i7 10th Gen · 32GB · 512GB NVMe",
    category: "Refurbished Laptop",
    price: 37000,
    oldPrice: 140000,
    badge: "Best Value",
    brand: "Dell",
    stock: "In Stock",
    condition: "Refurbished",
    warranty: "Up to 6 months*",
    rating: 4.8,
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=85",
    specs: {
      Processor: "Intel Core i7 10th Gen",
      Memory: "32GB DDR4",
      Storage: "512GB NVMe SSD",
      Display: "14-inch Full HD",
      OS: "Windows 11 Pro",
      Use: "Business / Coding / Office",
    },
  },
  {
    id: 2,
    name: "HP ProBook 440 G8",
    subtitle: "Core i5 11th Gen · Windows 11 Pro",
    category: "Refurbished Laptop",
    price: 26000,
    oldPrice: 98000,
    badge: "Hot Deal",
    brand: "HP",
    stock: "Low Stock",
    condition: "Refurbished",
    warranty: "Up to 6 months*",
    rating: 4.7,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=85",
    specs: {
      Processor: "Intel Core i5 11th Gen",
      Memory: "16GB DDR4",
      Storage: "512GB SSD",
      Display: "14-inch Full HD",
      OS: "Windows 11 Pro",
      Use: "Study / Office / Business",
    },
  },
  {
    id: 3,
    name: "MacBook Pro M1 Pro",
    subtitle: "14-inch · 16GB · 512GB SSD",
    category: "MacBook",
    price: 70000,
    oldPrice: 145000,
    badge: "Premium",
    brand: "Apple",
    stock: "In Stock",
    condition: "Pre-owned",
    warranty: "Store warranty*",
    rating: 4.9,
    image:
      "https://images.unsplash.com/photo-1511385348-a52b4a160dc2?auto=format&fit=crop&w=1200&q=85",
    specs: {
      Processor: "Apple M1 Pro",
      Memory: "16GB Unified",
      Storage: "512GB SSD",
      Display: "14-inch Liquid Retina XDR",
      OS: "macOS",
      Use: "Editing / Development / Creative",
    },
  },
  {
    id: 4,
    name: "Custom i5 Desktop",
    subtitle: "8th Gen · 8GB DDR4 · 256GB SSD",
    category: "Desktop",
    price: 20900,
    oldPrice: 29900,
    badge: "3Y Warranty*",
    brand: "Custom",
    stock: "Build to Order",
    condition: "Custom Build",
    warranty: "Up to 3 years on selected parts*",
    rating: 4.8,
    image:
      "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=1200&q=85",
    specs: {
      Processor: "Intel Core i5 8th Gen",
      Memory: "8GB DDR4",
      Storage: "256GB SSD",
      Graphics: "Integrated / Upgradeable",
      Cabinet: "Custom",
      Use: "Office / Billing / Study",
    },
  },
  {
    id: 5,
    name: "RTX 3070 Twin Edge",
    subtitle: "8GB GDDR6 · Pre-owned",
    category: "Gaming",
    price: 24499,
    oldPrice: 70000,
    badge: "Gaming",
    brand: "NVIDIA",
    stock: "Low Stock",
    condition: "Pre-owned",
    warranty: "Ask store*",
    rating: 4.7,
    image:
      "https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=1200&q=85",
    specs: {
      GPU: "GeForce RTX 3070",
      Memory: "8GB GDDR6",
      Cooling: "Twin Fan",
      Target: "1440p Gaming",
      PSU: "650W+ recommended",
      Use: "Gaming / Rendering",
    },
  },
  {
    id: 6,
    name: "GTX 1660 Super",
    subtitle: "6GB GDDR6 · Twin Fan",
    category: "Gaming",
    price: 12999,
    oldPrice: 40000,
    badge: "Limited",
    brand: "NVIDIA",
    stock: "In Stock",
    condition: "Pre-owned",
    warranty: "Ask store*",
    rating: 4.6,
    image:
      "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=85",
    specs: {
      GPU: "GeForce GTX 1660 Super",
      Memory: "6GB GDDR6",
      Cooling: "Twin Fan",
      Target: "1080p Gaming",
      PSU: "450W+ recommended",
      Use: "Gaming / Editing",
    },
  },
  {
    id: 7,
    name: "Intel Core i5 Processor",
    subtitle: "Performance upgrade for everyday PCs",
    category: "Components",
    price: 2100,
    oldPrice: 4000,
    badge: "Upgrade",
    brand: "Intel",
    stock: "In Stock",
    condition: "Pre-owned",
    warranty: "Ask store*",
    rating: 4.5,
    image:
      "https://images.unsplash.com/photo-1555617778-02518510b9fa?auto=format&fit=crop&w=1200&q=85",
    specs: {
      Type: "Desktop Processor",
      Family: "Intel Core i5",
      Socket: "Confirm before purchase",
      Cooling: "Depends on bundle",
      Use: "PC Upgrade",
      Note: "Compatibility check required",
    },
  },
  {
    id: 8,
    name: "HP EliteDesk Mini",
    subtitle: "Compact business PC · SSD ready",
    category: "Desktop",
    price: 13500,
    oldPrice: 19000,
    badge: "Business",
    brand: "HP",
    stock: "In Stock",
    condition: "Refurbished",
    warranty: "Up to 6 months*",
    rating: 4.7,
    image:
      "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=85",
    specs: {
      Processor: "Intel Core series",
      Memory: "8GB DDR4",
      Storage: "SSD ready",
      Form: "Mini PC",
      OS: "Windows compatible",
      Use: "Business / POS / Office",
    },
  },
];

export const reviews = [
  {
    name: "Krishna Panwar",
    text: "Purchased a Lenovo ThinkPad. Great product and best service after using the laptop.",
  },
  {
    name: "Vinay Minsu",
    text: "Best price for new and refurbished PC parts with helpful customer service.",
  },
  {
    name: "Rajendra Rajput",
    text: "Good-condition laptops and computers with strong value for money.",
  },
];

export const brands = ["All", "Dell", "HP", "Apple", "NVIDIA", "Intel", "Custom"];
